c4_amp:
  Living Room:
    ip: 192.168.0.145
    channel: 1
    port: 8750
    sources:
      2: WiiM
      1: EA5
  Kitchen:
    ip: 192.168.0.145
    channel: 2
    port: 8750
    sources:
      2: WiiM
      1: EA5
  Garage:
    ip: 192.168.0.145
    channel: 3
    port: 8750
    sources:
      2: WiiM
      1: EA5
  Casa Shea:
    ip: 192.168.0.145
    channel: 4
    port: 8750
    sources:
      2: WiiM
      1: EA5
  Game Room:
    ip: 192.168.0.145
    channel: 5
    port: 8750
    sources:
      2: WiiM
      1: EA5
  Back Yard:
    ip: 192.168.0.145
    channel: 6
    port: 8750
    sources:
      2: WiiM
      1: EA5
  Bedroom:
    ip: 192.168.0.145
    channel: 7
    port: 8750
    sources:
      2: WiiM
      1: EA5
  CraftZone:
    ip: 192.168.0.145
    channel: 8
    port: 8750
    sources:
      2: WiiM
      1: EA5
